FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends docker-io && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY . .

CMD ["bash", "/app/ci.sh"]
